apiVersion: kabanero.io/v1alpha2
kind: Stack
metadata:
  name: test
  namespace: kabanero
spec:
  name: test
  versions:
  - images:
    - id: node js
      image: docker.io/appsody/nodejs
    pipelines:
    - gitRelease: {}
      https:
        url: https://github.com/mchenggit/user-app-gitops/blob/master/pipelines/odotechpreview-pipelines.tar.gz?raw=true
      id: default
      sha256: cb6926f5c73de1e62fa68a179952c1c1d4a3e7a0594d60436d8df77b27964e33
    version: 0.4.0
    devfile: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/devfile.yaml
