apiVersion: kabanero.io/v1alpha2
kind: Stack
metadata:
  name: test
  namespace: kabanero
spec:
  name: test
  versions:
  - images:
    - id: node js
      image: docker.io/appsody/nodejs
    pipelines:
    - gitRelease: {}
      https:
        url: https://github.com/mchenggit/user-app-gitops/blob/master/pipelines/pipelines-pipelines.tar.gz?raw=true
      id: default
      sha256: 908a1bf86fb8690b1e17d4f7f31ece8b610ae78124ef7c83157e3354b3dfa38a
    version: 0.4.0
    devfile: https://raw.githubusercontent.com/odo-devfiles/registry/master/devfiles/nodejs/devfile.yaml
